services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - 11435:11434
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

volumes:
  qdrant_data:
  ollama_data:
