spring:
  application:
    name: ask-ai
  ai:
    vectorstore:
      qdrant:
        host: localhost
        port: 6334
        collection-name: repo_collection
        use-tls: false
        initialize-schema: true
    model:
      embedding: ollama
    ollama:
      base-url: http://localhost:11434
      embedding:
        options:
          model: nomic-embed-text:latest
      chat:
        options:
          model: gemma3:12b
